# -*- coding: utf-8 -*-
"""config_legacy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rt59zTlydv0ZTcEgUOfcS8VJhxhq_YAA
"""

import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(BASE_DIR, "..", ".."))

ML_ARCHIVE_DIR = os.path.join(REPO_ROOT, "ml", "archive")

VIDEO_PATH = os.path.join(BASE_DIR, "demo-parking.mp4")
FRAME_PATH = os.path.join(BASE_DIR, "parking-frame.jpg")
SPOTS_PATH = os.path.join(BASE_DIR, "spots.json")

OUTPUT_JSON = os.path.join(BASE_DIR, "prediction_output.json")
OUTPUT_IMAGE = os.path.join(BASE_DIR, "annotated_predictions.jpg")

MODEL_PATH = os.path.join(ML_ARCHIVE_DIR, "random_forest_parking_model_old.pkl")