# -*- coding: utf-8 -*-
"""extract_frame_legacy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rt59zTlydv0ZTcEgUOfcS8VJhxhq_YAA
"""

import os
import sys
import cv2

CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.append(CURRENT_DIR)

from config_legacy import VIDEO_PATH, FRAME_PATH

TARGET_FRAME = 700


def main():
    print("VIDEO_PATH:", VIDEO_PATH)
    print("FRAME_PATH:", FRAME_PATH)
    print("TARGET_FRAME:", TARGET_FRAME)

    if not os.path.exists(VIDEO_PATH):
        raise FileNotFoundError(f"Could not find video at: {VIDEO_PATH}")

    cap = cv2.VideoCapture(VIDEO_PATH)
    if not cap.isOpened():
        raise RuntimeError(f"Could not open video: {VIDEO_PATH}")

    current_frame = 0
    saved = False

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        if current_frame == TARGET_FRAME:
            cv2.imwrite(FRAME_PATH, frame)
            print(f"Saved frame {TARGET_FRAME} to {FRAME_PATH}")
            saved = True
            break

        current_frame += 1

    cap.release()

    if not saved:
        print("Could not extract the requested frame. Try a smaller TARGET_FRAME.")


if __name__ == "__main__":
    main()