# -*- coding: utf-8 -*-
"""infer_video.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Whw0wlZc87Ocb45ycylpVW3sxPW3Eunt
"""

import os
import sys
import json
import cv2
import numpy as np

CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
SCRIPTS_DIR = os.path.abspath(os.path.join(CURRENT_DIR, ".."))
sys.path.append(SCRIPTS_DIR)

from config import VIDEO_PATH, SPOTS_PATH, OUTPUT_JSON, OUTPUT_IMAGE, MODEL_PATH, ML_DIR

sys.path.append(ML_DIR)
from predict_spot import load_model, predict_spot

SAMPLE_EVERY_FRAMES = 10


def load_spots(spots_path):
    with open(spots_path, "r") as f:
        return json.load(f)


def crop_polygon_region(frame, polygon_points):
    pts = np.array(polygon_points, dtype=np.int32)

    x, y, w, h = cv2.boundingRect(pts)
    crop = frame[y:y+h, x:x+w].copy()

    shifted_pts = pts - np.array([x, y])

    mask = np.zeros((h, w), dtype=np.uint8)
    cv2.fillPoly(mask, [shifted_pts], 255)

    masked_crop = cv2.bitwise_and(crop, crop, mask=mask)

    return masked_crop, (x, y, w, h), pts


def infer_single_frame(frame, spots, model):
    predictions = []
    annotated = frame.copy()

    for spot in spots:
        spot_id = spot["id"]
        polygon_points = spot["points"]

        masked_crop, bbox, pts = crop_polygon_region(frame, polygon_points)
        pred = predict_spot(masked_crop, model)
        predictions.append(pred)

        color = (0, 255, 0) if pred == 0 else (0, 0, 255)
        label = f"{spot_id}: {'empty' if pred == 0 else 'occupied'}"

        cv2.polylines(annotated, [pts], isClosed=True, color=color, thickness=2)

        x, y, w, h = bbox
        cv2.putText(
            annotated,
            label,
            (x, y - 5),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.5,
            color,
            2
        )

    return predictions, annotated


def save_outputs(predictions, annotated, frame_index, timestamp_sec):
    result = {
        "frame_index": frame_index,
        "timestamp_sec": round(timestamp_sec, 2),
        "total_spots": len(predictions),
        "available_spots": predictions.count(0),
        "occupied_spots": predictions.count(1),
        "spots": predictions
    }

    with open(OUTPUT_JSON, "w") as f:
        json.dump(result, f, indent=2)

    cv2.imwrite(OUTPUT_IMAGE, annotated)

    print(
        f"Frame {frame_index} | "
        f"t={round(timestamp_sec, 2)}s | "
        f"available={result['available_spots']} | "
        f"occupied={result['occupied_spots']}"
    )


def main():
    if not os.path.exists(VIDEO_PATH):
        raise FileNotFoundError(f"Could not find video: {VIDEO_PATH}")

    if not os.path.exists(SPOTS_PATH):
        raise FileNotFoundError(f"Could not find spots file: {SPOTS_PATH}")

    if not os.path.exists(MODEL_PATH):
        raise FileNotFoundError(f"Could not find model file: {MODEL_PATH}")

    spots = load_spots(SPOTS_PATH)
    model = load_model(MODEL_PATH)

    cap = cv2.VideoCapture(VIDEO_PATH)
    if not cap.isOpened():
        raise RuntimeError(f"Could not open video: {VIDEO_PATH}")

    fps = cap.get(cv2.CAP_PROP_FPS)
    if fps <= 0:
        fps = 24.0

    frame_index = 0
    processed_frames = 0

    print("Starting video inference...")
    print(f"Video path: {VIDEO_PATH}")
    print(f"FPS detected: {fps}")
    print(f"Processing every {SAMPLE_EVERY_FRAMES} frames")

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        if frame_index % SAMPLE_EVERY_FRAMES == 0:
            timestamp_sec = frame_index / fps
            predictions, annotated = infer_single_frame(frame, spots, model)
            save_outputs(predictions, annotated, frame_index, timestamp_sec)
            processed_frames += 1

        frame_index += 1

    cap.release()

    print("\nFinished video inference.")
    print(f"Total frames read: {frame_index}")
    print(f"Frames processed: {processed_frames}")
    print(f"Latest JSON saved to: {OUTPUT_JSON}")
    print(f"Latest annotated image saved to: {OUTPUT_IMAGE}")


if __name__ == "__main__":
    main()