# -*- coding: utf-8 -*-
"""infer_frame.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V7yTP-l26Jc_LjpJZdVc8fKYWBN3IJEy
"""

import os
import sys
import json
import cv2
import numpy as np

CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
SCRIPTS_DIR = os.path.abspath(os.path.join(CURRENT_DIR, ".."))
sys.path.append(SCRIPTS_DIR)

from config import FRAME_PATH, SPOTS_PATH, OUTPUT_JSON, OUTPUT_IMAGE, MODEL_PATH, ML_DIR

sys.path.append(ML_DIR)
from predict_spot import load_model, predict_spot


def load_spots(spots_path):
    with open(spots_path, "r") as f:
        return json.load(f)


def crop_polygon_region(frame, polygon_points):
    pts = np.array(polygon_points, dtype=np.int32)

    frame_h, frame_w = frame.shape[:2]

    pts[:, 0] = np.clip(pts[:, 0], 0, frame_w - 1)
    pts[:, 1] = np.clip(pts[:, 1], 0, frame_h - 1)

    x_min = int(np.min(pts[:, 0]))
    x_max = int(np.max(pts[:, 0]))
    y_min = int(np.min(pts[:, 1]))
    y_max = int(np.max(pts[:, 1]))

    crop = frame[y_min:y_max, x_min:x_max].copy()

    if crop.size == 0:
        raise ValueError(f"Empty crop for polygon: {polygon_points}")

    shifted_pts = pts - np.array([x_min, y_min])

    mask = np.zeros(crop.shape[:2], dtype=np.uint8)
    cv2.fillPoly(mask, [shifted_pts], 255)

    print("crop shape:", crop.shape, "| mask shape:", mask.shape)

    masked_crop = cv2.bitwise_and(crop, crop, mask=mask)

    return masked_crop, (x_min, y_min, x_max - x_min, y_max - y_min), pts


def main():
    print("CURRENT_DIR:", CURRENT_DIR)
    print("SCRIPTS_DIR:", SCRIPTS_DIR)
    print("FRAME_PATH:", FRAME_PATH)
    print("SPOTS_PATH:", SPOTS_PATH)
    print("MODEL_PATH:", MODEL_PATH)

    frame = cv2.imread(FRAME_PATH)
    if frame is None:
        raise FileNotFoundError(f"Could not load frame: {FRAME_PATH}")

    if not os.path.exists(SPOTS_PATH):
        raise FileNotFoundError(f"Could not find spots file: {SPOTS_PATH}")

    if not os.path.exists(MODEL_PATH):
        raise FileNotFoundError(f"Could not find model file: {MODEL_PATH}")

    spots = load_spots(SPOTS_PATH)
    model = load_model(MODEL_PATH)

    predictions = []
    annotated = frame.copy()

    for spot in spots:
        spot_id = spot["id"]
        polygon_points = spot["points"]
        
        print(f"Processing spot {spot_id} with points: {polygon_points}")
        masked_crop, bbox, pts = crop_polygon_region(frame, polygon_points)
        pred = predict_spot(masked_crop, model)
        predictions.append(pred)

        color = (0, 255, 0) if pred == 0 else (0, 0, 255)
        label = f"{spot_id}: {'empty' if pred == 0 else 'occupied'}"

        cv2.polylines(annotated, [pts], isClosed=True, color=color, thickness=2)

        x, y, w, h = bbox
        cv2.putText(
            annotated,
            label,
            (x, y - 5),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.5,
            color,
            2
        )

    result = {
        "total_spots": len(predictions),
        "available_spots": predictions.count(0),
        "occupied_spots": predictions.count(1),
        "spots": predictions
    }

    with open(OUTPUT_JSON, "w") as f:
        json.dump(result, f, indent=2)

    cv2.imwrite(OUTPUT_IMAGE, annotated)

    print("Predictions:", predictions)
    print("Available spots:", result["available_spots"])
    print("Occupied spots:", result["occupied_spots"])
    print(f"Saved JSON to: {OUTPUT_JSON}")
    print(f"Saved annotated image to: {OUTPUT_IMAGE}")


if __name__ == "__main__":
    main()