# -*- coding: utf-8 -*-
"""predict_spot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ECM5r3tQRZ0QXTdkkSYAcn64xmr9o4FT
"""

import cv2
import joblib

IMG_SIZE = (32, 32)


def load_model(model_path: str):
    return joblib.load(model_path)


def preprocess_image(image):
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    resized = cv2.resize(gray, IMG_SIZE)
    features = resized.flatten().reshape(1, -1)
    return features


def predict_spot(image, model):
    features = preprocess_image(image)
    prediction = model.predict(features)[0]
    return int(prediction)


def predict_from_image_path(image_path: str, model_path: str):
    image = cv2.imread(image_path)
    if image is None:
        raise FileNotFoundError(f"Image not found at path: {image_path}")

    model = load_model(model_path)
    prediction = predict_spot(image, model)
    return prediction


if __name__ == "__main__":
    sample_image_path = "sample_spot.jpg"
    model_path = "random_forest_parking_model.pkl"

    prediction = predict_from_image_path(sample_image_path, model_path)
    label = "empty" if prediction == 0 else "occupied"

    print(f"Prediction: {prediction} ({label})")