# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11CLgL9zKCbTGTVWgrw3zxY_r2vjEiSY7
"""

import os

SCRIPTS_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(SCRIPTS_DIR, ".."))
ML_DIR = os.path.join(REPO_ROOT, "ml")

ANNOTATION_DIR = os.path.join(SCRIPTS_DIR, "annotation")
INFERENCE_DIR = os.path.join(SCRIPTS_DIR, "inference")
DEMO_DIR = os.path.join(SCRIPTS_DIR, "demo")

FRAME_PATH = os.path.join(ANNOTATION_DIR, "parking-frame.jpg")
SPOTS_PATH = os.path.join(ANNOTATION_DIR, "spots.json")
VIDEO_PATH = os.path.join(DEMO_DIR, "demo-parking.mp4")

MODEL_PATH = os.path.join(ML_DIR, "random_forest_parking_model.pkl")

OUTPUT_JSON = os.path.join(INFERENCE_DIR, "prediction_output.json")
OUTPUT_IMAGE = os.path.join(INFERENCE_DIR, "annotated_predictions.jpg")