# -*- coding: utf-8 -*-
"""annotate_spots.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ylhj5GFcVCN3XyQvko5OfFbkLnJM2AFi
"""

# Tool to mark the spots

import cv2
import sys
import json
import os
import numpy as np

CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
SCRIPTS_DIR = os.path.abspath(os.path.join(CURRENT_DIR, ".."))
sys.path.append(SCRIPTS_DIR)

from config import FRAME_PATH, SPOTS_PATH

image = cv2.imread(FRAME_PATH)

if image is None:
    raise FileNotFoundError(
        f"Could not load image at: {image_path}\n"
        f"Make sure the frame exists and is named 'parking-frame.jpg'."
    )

base_image = image.copy()
spots = []
current_points = []


def redraw():
    global image
    image = base_image.copy()

    for spot in spots:
        pts = np.array(spot["points"], dtype=np.int32)
        cv2.polylines(image, [pts], isClosed=True, color=(255, 0, 0), thickness=2)

        x, y = pts[0]
        cv2.putText(
            image,
            str(spot["id"]),
            (x, y - 5),
            cv2.FONT_HERSHEY_SIMPLEX,
            0.6,
            (0, 0, 255),
            2
        )

    if len(current_points) > 0:
        for pt in current_points:
            cv2.circle(image, tuple(pt), 4, (0, 255, 0), -1)

        if len(current_points) > 1:
            pts = np.array(current_points, dtype=np.int32)
            cv2.polylines(image, [pts], isClosed=False, color=(0, 255, 255), thickness=1)


def mouse_callback(event, x, y, flags, param):
    global current_points, spots

    if event == cv2.EVENT_LBUTTONDOWN:
        current_points.append([x, y])
        print(f"Clicked: ({x}, {y})")
        redraw()

        if len(current_points) == 4:
            spots.append({
                "id": len(spots) + 1,
                "points": current_points.copy()
            })
            print(f"Spot {len(spots)} saved: {current_points}")
            current_points = []
            redraw()


cv2.namedWindow("Annotate Parking Spots")
cv2.setMouseCallback("Annotate Parking Spots", mouse_callback)

print("Instructions:")
print("- Click 4 corners for each parking spot")
print("- Recommended order: top-left, top-right, bottom-right, bottom-left")
print("- Press 's' to save")
print("- Press 'u' to undo last saved spot")
print("- Press 'c' to clear current unfinished spot")
print("- Press 'r' to reset all spots")
print("- Press 'q' to quit")

redraw()

while True:
    cv2.imshow("Annotate Parking Spots", image)
    key = cv2.waitKey(1) & 0xFF

    if key == ord("s"):
        with open(SPOTS_PATH, "w") as f:
            json.dump(spots, f, indent=2)
        print(f"Saved {len(spots)} spots to {SPOTS_PATH}")

    elif key == ord("u"):
        if spots:
            removed = spots.pop()
            print(f"Removed spot {removed['id']}")
            redraw()

    elif key == ord("c"):
        current_points = []
        print("Cleared current unfinished spot.")
        redraw()

    elif key == ord("r"):
        spots = []
        current_points = []
        print("Reset all spots.")
        redraw()

    elif key == ord("q"):
        print("Quitting.")
        break

cv2.destroyAllWindows()